# Do not edit this file, it was generated automatically by Taker build system

default: all
.PHONY: default

help:
	@echo 'Available commands:'
	@echo '                 all: Builds everything'
	@echo '                help: Prints this help'
.PHONY: help

all: src/aplusb src/code_libs
.PHONY: all

src/aplusb: src/aplusb.cpp
	{0} compile --exe=src/aplusb --lang=cpp.g++11 -- src/aplusb.cpp

src/code_libs: src/code_libs.cpp
	{0} compile --exe=src/code_libs --lang=cpp.g++14 --lib=lib -- src/code_libs.cpp
