# Do not edit this file, it was generated automatically by Taker build system

default: all
.PHONY: default

help:
	@echo 'Available commands:'
	@echo '                 all: Builds everything'
	@echo '                help: Prints this help'
.PHONY: help

all: genout src/aplusb src/code_libs
.PHONY: all

src/aplusb: src/aplusb.cpp
	{0} compile --exe=src/aplusb --lang=cpp.g++11 -- src/aplusb.cpp

src/code_libs: src/code_libs.cpp
	{0} compile --exe=src/code_libs --lang=cpp.g++14 --lib=lib -- src/code_libs.cpp

src/code_gen_out: src/code_gen_out.cpp
	{0} compile --exe=src/code_gen_out --lang=cpp.g++17 -- src/code_gen_out.cpp

genout: src/code_gen_out
	{0} run --lang=cpp.g++17 --profile=compiler -- src/code_gen_out arg1 arg2
	{0} run --lang=cpp.g++17 --profile=generator --work-dir=.. '--input=see '"'"'42'"'"'!' -q -- src/code_gen_out
.PHONY: genout
